name: "Release to s3"
description: "Release to s3"
author: "wangsha"
inputs:
  args:
    description: "s3pypi input arguments."
    required: true
  fail_on_error:
    description: |
      Exit code when s3pypi errors are found [true, false]. Defaults to 'true'.
    required: false
    default: "true"
outputs:
  output:
    description: "s3pypi output"
branding:
  color: "black"
  icon: "check-circle"
runs:
  using: "docker"
  image: "Dockerfile"