name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  s3pypi:
    runs-on: ubuntu-latest
    name: Release python package to s3
    steps:
      - uses: actions/checkout@v3
      - name: Release python package to s3
        id: release-s3
        uses: ./
        with:
          fail_on_error: "false"
          args: "--bucket pypi.mydomain.com -v"